---
title: "stat041_yyan1_dcastro2"
author: "Yichuan Yan"
date: "2/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For project 1, we decide to explore employment rates and salaries for college graduates based on majors. We used data provided by fivethirdyeight package as well as survey from the Federal Reserve.

```{r dataset}
library(fivethirtyeight)
library(ggplot2)
library(readr)
library(dplyr)
library(forcats)
library(ggthemes)
library(fontcm)
library(extrafont)
theme_set(theme_fivethirtyeight())
theme_update(plot.title = element_text(hjust = 0.5))
font_install(fontpkg='fontcm',prompt=TRUE)

# Edit to demonstrate how github does things -- Emma
```


```{r data_wrangling}
college <- data.frame(college_recent_grads)

#Dalia's code works with this: ~/Labs/stat041_p1_grp14/labor-market-for-recent-college-grads.csv
college_fed <- read_csv("~/Labs/stat041_p1_grp14/labor-market-for-recent-college-grads.csv")
college_fed <- college_fed[1:74,]
overall_fed <- college_fed[74,]
college_fed <- college_fed[-74,]
college.join <- inner_join(college_fed,college,by = c("Major" = "major"))

#filter names of ed, misc, 

college.join$Major[college.join$Major == "Early Childhood Education"] <- "Early Childhood Ed."
college.join$Major[college.join$Major == "Elementary Education"] <- "Elementary Ed."
college.join$Major[college.join$Major == "General Education"] <- "Gen Ed."
college.join$Major[college.join$Major == "Miscellaneous Education"] <- "Misc. Ed."
college.join$Major[college.join$Major == "General Social Science"] <- "Gen. Social Science"
college.join$Major[college.join$Major == "Electrical Engineering"] <- "Electrical Engin."
college.join$Major[college.join$Major == "General Business"] <- "Gen. Business"
college.join$Major[college.join$Major == "Construction Services"] <- "Construction Serv."
college.join$Major[college.join$Major == "Chemical Engineering"] <- "Chemical Engin."
college.join$Major[college.join$Major == "General Engineering"] <- "Gen. Engin."
college.join$Major[college.join$Major == "Civil Engineering"] <- "Civil Engin."
college.join$Major[college.join$Major == "Computer Engineering"] <- "Computer Engin."
college.join$Major[college.join$Major == "Aerospace Engineering"] <- "Aerospace Engin."
college.join$Major[college.join$Major == "Miscellaneous Engineering"] <- "Misc. Engin."
college.join$Major[college.join$Major == "Mechanical Engineering"] <- "Mechanical Engin."
college.join$Major[college.join$Major == "Engineering Technologies"] <- "Engin. Tech."
college.join$Major[college.join$Major == "General Social Sciences"] <- "Gen. Social Sciences"













```

```{r visualization}
#Instruction source: https://rstudio-pubs-static.s3.amazonaws.com/7433_4537ea5073dc4162950abb715f513469.html
college.join$Major<- factor(college.join$Major,levels = college.join$Major[order(college.join$`Unemployment Rate`)])

par(mar=c(6,6,6,3)+.1)
ggplot(college.join) + 
  geom_col(mapping = aes(Major,`unemployment_rate`*100), alpha = 0.2, fill = "orange", color = FALSE, width = 0.8) +
  geom_col(mapping = aes(Major,`Unemployment Rate`), alpha = 0.6, fill = "midnightblue", color = FALSE, width = 0.8) + 
  coord_flip() + 
  labs(y = "Unemployment Rate (%)", x = "Undergraduate Major", title = "Unemployment Rate by College Major") +
  theme(axis.text.x = element_text(angle = 0, vjust = 1 , hjust = 1), 
        axis.line.x = element_line(colour = "grey80"), 
        axis.title = element_text(size = 10), 
        axis.text = element_text(size = 8), 
        title = element_text(size = 12)
  )

ggplot(college.join) + 
  geom_col(mapping = aes(Major,(`Median Wage Mid-Career` - `Median Wage Early Career`)/`Median Wage Early Career`*100), alpha = 0.2, fill = "green", color = FALSE, width = 0.8) +
  geom_col(mapping = aes(Major,`Unemployment Rate`), alpha = 0.6, fill = "midnightblue", color = FALSE, width = 0.8) + 
  coord_flip() + 
  labs(y = "Unemployment Rate (%)", x = "Undergraduate Major", title = "Unemployment vs. Wage Growth") +
  theme(axis.text.x = element_text(angle = 0, vjust = 1 , hjust = 1), 
        axis.line.x = element_line(colour = "grey80"), 
        axis.title = element_text(size = 12, color = "aquamarine3"), 
        axis.text = element_text(size = 12), 
        title = element_text(size = 9, color = "aquamarine3")
  )

#share of women per major graph
 college.join$Major<- factor(college.join$Major,levels = college.join$Major[order(college.join$sharewomen)])


ggplot(college.join, mapping = aes(y = sharewomen*100, x = Major)) + geom_col(color = "lightslateblue") + labs(y = "Major", x = "Share of Women (%)", title = "Share of Women in Each Major") + coord_flip() +
        theme(axis.text.x = element_text(angle = 0, vjust = 1 , hjust = 1), 
        axis.line.x = element_line(colour = "black"), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 12), 
        title = element_text(size = 15, color = "aquamarine3"),
        axis.title.x = element_text(size = 14, colour = "mediumorchid3"),
        axis.title.y = element_text(size = 14, colour = "mediumorchid3")
)

#select(college.join, contains("women"))

#share of women per major graph plot
 college.join$Major<- factor(college.join$Major,levels = college.join$Major[order(college.join$sharewomen)])


ggplot(college.join, mapping = aes(x = sharewomen*100, y = Major)) + geom_point(color = "royalblue3") + labs(y = "Major", x = "Share of Women (%)", title = "Share of Women in Each Major") + theme(axis.text.x = element_text(angle = 0, vjust = 1 , hjust = 1), 
        axis.line.x = element_line(colour = "black"), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 12), 
        title = element_text(size = 15, color = "aquamarine3"),
        axis.title.x = element_text(size = 14, colour = "mediumorchid3"),
        axis.title.y = element_text(size = 14, colour = "mediumorchid3")
        
)

#select(college.join, contains("major"))
#Questions for Prof
#What is interactive style
#Are the way that the graphs are made/merged alright?

#to rejoin majors we want again in the new innerjoin = mutate(majors_new, recode('econ' = "economics"))

#information on two axis https://rpubs.com/MarkusLoew/226759
```
